### PR TITLE
updates for purescript-0.11

### LINKED ISSUE #33: Support "purs ide client/server" commands
PureScript 0.11 will start moving towards a singled executable for PureScript projects, including moving from "psc-ide-server/psc-ide-client" to "purs ide server/purs ide client".

### PR DESCRIPTION
**Pull request by coot**
resolves: #33

### CODE REVIEW

**Comment by anilanar** [comment]
Hmm, this branch doesn't work for me in `neovim`:

```
$ pulp --version
Pulp version 11.0.0
purs version 0.11.3
```

```
Error detected while processing /Users/anilanar/.vim/bundle/psc-ide-vim/ftplugin/purescript_pscide.vim:
line   54:
E121: Undefined variable: v:none
E15: Invalid expression: v:none
```

-----

Nevermind, I checked out `purescript-0.11` instead of  `sync-purescript-0.11`.

**Comment by coot** [comment]
@anilanar can you pull and check if it works now for you.

**Comment by alexmingoia** [comment]
This wasn't working for me and I traced it to this line: https://github.com/FrigoEU/psc-ide-vim/blob/7bc6ca951de67643738a6981d2446dee34c4cc40/syntax_checkers/purescript/pscide.vim#L34 which should be changed to `purs --version`. With that change everything works.

**Comment by FrigoEU** [comment]
I think most people are using 0.11 by now so I'll merge this in, including @alexmingoia's fix for syntastic. Thanks for the help!

**Pull request merged**
