### PR TITLE
Add option "--editor-mode" on project startup

### PR DESCRIPTION
**Pull request by VlkrS**
Reference: 
https://github.com/purescript/purescript/issues/2249

This fixes the reported issue in psc-ide with very high CPU consumption even when idle on my end.

### CODE REVIEW

**Comment by alextes** [comment]
From what I understand vscode has this as an option, as I don't understand the full ramifications I'd prefer we have an option to turn it on as well. Would you be interested in making that change @VlkrS ?

**Comment by kritzcreek** [comment]
The flag shouldn't be necessary anymore with current versions of the IDE server.

**Comment by paluh** [comment]
EDIT: @kritzcreek was 2.37 seconds faster with his response ;-)

---

@alextes - I think that we should close this all together as `purs ide server` deprecates usage of `--editor-mode` (it starts in this mode by default now).

**Comment by alextes** [comment]
Great, done! Thanks for the help 🙏 .

**Pull request closed without merging**
